### ISSUE TITLE
Compatibility Issue

### ISSUE THREAD

**Issue by TrentXV** [rupak0577/FishDex#1]
When Using with latest version of More New Fish (https://www.nexusmods.com/stardewvalley/mods/3578?tab=description) I get the error below:

[21:35:21 TRACE FishDex] Opening fish menu
[21:35:21 ERROR FishDex] Something went wrong opening fish menu:
System.NullReferenceException: Referência de objeto não definida para uma instância de um objeto.
   em FishDex.Components.FishMenu..ctor(DataParser parser, IMonitor monitor, IReflectionHelper reflectionHelper, Int32 scroll, Boolean showAll) na C:\Users\ru481\Documents\Visual Studio 2017\Projects\FishDex\FishDex\Components\FishMenu.cs:linha 57
   em FishDex.ModEntry.<ToggleFishMenu>b__7_0() na C:\Users\ru481\Documents\Visual Studio 2017\Projects\FishDex\FishDex\ModEntry.cs:linha 124
   em FishDex.Helpers.ErrorHandler.InterceptErrors(IMonitor monitor, String verb, String detailedVerb, Action action, Action`1 onError) na C:\Users\ru481\Documents\Visual Studio 2017\Projects\FishDex\FishDex\Helpers\ErrorHandler.cs:linha 40

**Comment by rupak0577** [comment]
This is probably due to the new fishes that the mod adds to the game. I will see if I can find some free time to fix this.

**Comment by TrentXV** [comment]
Thanks

**Comment by TrentXV** [comment]
It was an error in my mod, please disconsider. Thanks for the attention.
