### ISSUE TITLE
Info Incorrect on some Fish

### ISSUE THREAD

**Issue by ImmortalZypther** [rupak0577/FishDex#3]
Angler should be Fall only
Blobfish is Winter only
Carp is all seasons
Catfish is Spring, Fall, and Summer (Only in the Secret Woods)
Crimsonfish is summer
Glacierfish can be caught in the rain
Legend is Spring only
Midnight Squid is Winter only
Sardine is Spring, Fall, Winter
Spook Fish is Winter only
Sunfish can be caught in the sun and the wind (This is the only fish that has a mention of the wind weather)
Super Cucumber is Summer and Fall
Tiger Trout is Fall and Winter

I've tested with the "ShowAll" option in the config, the issue remains.
I've also tested without any other mods, the issue remains.
I haven't personally caught all these fish to verify the information, but I have at least caught the Super Cucumber in Fall.

Tiny request as well: For seasons and weathers, is it possible to list "all" instead of each season individually ("all" instead of "spring | summer | fall | winter")? It'd save some space for people with smaller screens.

If you want me to test anything else, I'll be glad to assist.

**Comment by rupak0577** [comment]
Thanks for the bug report. All the info is parsed from the game's internal data directly so I am not sure where the issue is. I will take a look though.

> For seasons and weathers, is it possible to list "all" instead of each season individually

Sure.

**Comment by ImmortalZypther** [comment]
I'm not versed in how this game stores data, but I've found a bit more information on fish:
Super Cucumber is Summer, Fall, and Winter (Only in the Night Market)
Octopus is Summer and Winter (Only in the Night Market)

I've also found something interesting, there's a spreadsheet with some matching incorrect information as you:
https://docs.google.com/spreadsheets/d/1uA2IQ_uMLmvEZa64P3ZVMkoGGM8qMqIWAfRYsnyhGRc/edit#gid=154714532

Here is the wiki page along with another spreadsheet containing the correct information:
https://stardewvalleywiki.com/Fish
https://docs.google.com/spreadsheets/d/1Cr7p-d7OTLz3AMOB8vbU9bWvFWHmp7Evzm5RWaZr7vM/edit#gid=0

Maybe an update changed some information on the fish so your code is thrown off a bit?
If I had to pick something, I'd blame the Night Market. It's the newest addition I can think of with new fish and new times fish can be caught.
The Super Cucumber and Octopus specifically, they go out of their normal seasons only during the Night Market.

**Comment by rupak0577** [comment]
@ImmortalZypther Okay, so looks like I have been parsing the data wrong since the start! According to the [modding wiki](https://stardewvalleywiki.com/Modding:Fish_data), the file that contains the fish data also contains the seasons for each fish but that is ignored and instead another file is used to figure out the seasons. Currently, I am using the ignored data directly so guess I probably forgot about it while writing the parsing code.

Thank you once again for the report or I would have never caught it!

**Comment by ImmortalZypther** [comment]
No problem, I'm just happy you're still supporting this mod!
